<?php echo $this->flashSession->output();?> 

<form action="" method="post" enctype="multipart/form-data">
<center>
    <label>ชื่อกิจกรรม (event name)</label>
    <input type="text" class="form-control" placeholder="ชื่อกิจกรรม" required name="name">
    <br><label>วันที่ทำกิจกรรม (event date)</label>
    <input type="date" class="form-control" placeholder="mm/dd/yyyy" required name="date">
    <br><label>รายละเอียดของกิจกรรม (event detail)</label>
    <textarea class="form-control" placeholder="รายละเอียด" required rows="4" name="details"></textarea>
    <br><label>รูปภาพประกอบ (event picture)</label>
    <div class="custom-file">
          <input type="file" name="photo"  class="custom-file-input"  >
          <label class="custom-file-label" >Choose file</label>
    </div>
    <hr><button type="submit" class="btn btn-light">submit</button>
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
</center>
</form>